"use client";
import { useState } from "react";
import {cashFlowBridge,chartDomain} from "@/lib/cash-flow-chart";
import type {FreeCashFlowYear} from "./ProjectedCashFlows";
import {formatCompactCurrency} from "./format";
const chartWidth=760,left=65,right=24,top=48,bottom=252;
function scale(values:number[]){const d=chartDomain(values);return {domain:d,y:(v:number)=>bottom-(v-d.min)/(d.max-d.min)*(bottom-top)};}
function ChartGrid({values}:{values:number[]}){const {domain,y}=scale(values);return <>{[0,1,2,3,4].map(i=>{const value=domain.min+(domain.max-domain.min)*i/4;return <g key={i}><line x1={left} x2={chartWidth-right} y1={y(value)} y2={y(value)} className="chart-gridline"/><text x={left-10} y={y(value)+4} textAnchor="end">{formatCompactCurrency(value)}</text></g>})}<line x1={left} x2={chartWidth-right} y1={y(0)} y2={y(0)} className="chart-zero"/></>}
export default function CashFlowCharts({rows,showBridge=false}:{rows:FreeCashFlowYear[];showBridge?:boolean}){
 const [selectedYear,setSelectedYear]=useState<number|null>(null);
 if(!rows.length || rows.some(row=>!Number.isFinite(row.fcf))) return <section className="status-warning" role="status">Annual cash flows are unavailable; no substitute values are plotted.</section>;
 const row=rows.find(r=>r.year===selectedYear)??rows[0];
 const {y}=scale(rows.map(r=>r.fcf)),spacing=(chartWidth-left-right)/rows.length,barWidth=Math.min(100,spacing*.72);
 let steps:ReturnType<typeof cashFlowBridge>=[];let bridgeError='';
 if(showBridge)try{steps=cashFlowBridge(row)}catch(error){bridgeError=error instanceof Error?error.message:'Cash flow bridge unavailable.'}
 const bridgeValues=steps.flatMap(s=>[s.start,s.end]); const bridgeY=bridgeValues.length?scale(bridgeValues).y:null;
 return <>
  <section className="panel model-chart-panel"><h2>Annual free cash flow</h2><p>Base-case projected FCFF · USD · Near-term and maturation forecast</p><div className="model-chart-scroll" tabIndex={0} aria-label="Annual free cash flow chart; scroll on small screens"><svg className="model-annual-chart" viewBox={`0 0 ${chartWidth} 310`} role="img" aria-label="Base-case annual free cash flow in US dollars"><title>Base-case annual free cash flow</title><ChartGrid values={rows.map(r=>r.fcf)}/>{rows.map((r,i)=>{const x=left+spacing*(i+.5);return <g key={r.year}><rect x={x-barWidth/2} y={Math.min(y(0),y(r.fcf))} width={barWidth} height={Math.abs(y(r.fcf)-y(0))} fill={r.fcf<0?'var(--signal)':'var(--chart-accent)'} rx="3"><title>Year {r.year}: {formatCompactCurrency(r.fcf)}</title></rect><text x={x} y={r.fcf>=0?y(r.fcf)-10:y(r.fcf)+18} textAnchor="middle" className="chart-value">{formatCompactCurrency(r.fcf)}</text><text x={x} y={bottom+28} textAnchor="middle">Year {r.year}</text></g>})}</svg></div></section>
  {showBridge && <section className="panel model-chart-panel"><div className="model-panel-heading"><div><h2>Cash flow bridge</h2><p>Projected components · USD · Base case</p></div><label className="model-year-control">Forecast year<select value={row.year} onChange={e=>setSelectedYear(Number(e.target.value))}>{rows.map(r=><option key={r.year} value={r.year}>Year {r.year}</option>)}</select></label></div>
   {bridgeError?<p className="status-warning" role="alert">{bridgeError} The projection table remains available.</p>:<><div className="model-chart-scroll" tabIndex={0} aria-label="Cash flow bridge chart; scroll on small screens"><svg className="model-bridge-chart" viewBox={`0 0 ${chartWidth} 310`} role="img" aria-label={`Year ${row.year} NOPAT plus depreciation minus capital expenditure minus change in working capital equals FCF`}><title>Year {row.year} cash flow bridge</title><ChartGrid values={bridgeValues}/>{steps.map((s,i)=>{const space=(chartWidth-left-right)/steps.length,x=left+space*(i+.5),barWidth=space*.65,y=bridgeY!;return <g key={s.label}><rect x={x-barWidth/2} y={Math.min(y(s.start),y(s.end))} width={barWidth} height={Math.abs(y(s.end)-y(s.start))} fill={s.total?'var(--chart-accent)':s.value<0?'var(--signal)':'var(--verdigris)'} rx="3"><title>{s.label}: {formatCompactCurrency(s.value)}; ending level {formatCompactCurrency(s.end)}</title></rect>{i<steps.length-2&&<line x1={x+barWidth/2} x2={x+space-barWidth/2} y1={y(s.end)} y2={y(s.end)} className="chart-connector"/>}<text x={x} y={Math.min(y(s.start),y(s.end))-10} textAnchor="middle" className="chart-value">{formatCompactCurrency(s.value)}</text><text x={x} y={bottom+28} textAnchor="middle">{s.label}</text></g>})}</svg></div><p className="model-chart-equation">Year {row.year}: NOPAT {formatCompactCurrency(row.nopat)} + D&amp;A {formatCompactCurrency(row.da)} − CapEx {formatCompactCurrency(row.capex)} − Δ NWC {formatCompactCurrency(row.change_in_nwc)} = FCF {formatCompactCurrency(row.fcf)}</p></>}
  </section>}
 </>;
}
